apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eyego-task-cluster
  region: us-east-1
  version: "1.33"

managedNodeGroups:
  - name: eyego-ng
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 2
    maxSize: 2
    volumeSize: 20
    labels:
      role: worker
    tags:
      nodegroup-role: worker
