apiVersion: apps/v1
kind: Deployment
metadata:
  name: eyego-app
  labels:
    app: eyego-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eyego-app
  template:
    metadata:
      labels:
        app: eyego-app
    spec:
      containers:
        - name: eyego-js-app
          image: 143480833705.dkr.ecr.us-east-1.amazonaws.com/eyego-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
