name: Automate Build, Push, and Deploy to AWS EKS

on:
  push:
    branches: [ "master" ]
    pull_request:
      branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to ECR
      env:
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      run: |
        IMAGE_TAG=latest
        docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
        docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: v1.29.0

    - name: Update kubeconfig for EKS
      run: |
        aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}

    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml

    - name: Wait for LoadBalancer and Get Public URL
      run: |
        echo "Waiting for LoadBalancer External IP..."
        for i in {1..30}; do
          EXTERNAL_HOSTNAME=$(kubectl get svc eyego-service -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
          if [[ -n "$EXTERNAL_HOSTNAME" ]]; then
              DEPLOY_URL="https://$EXTERNAL_HOSTNAME/eyego"
              echo "Service is available at: $DEPLOY_URL"
              echo "DEPLOY_URL=$DEPLOY_URL" >> $GITHUB_ENV
              break
          fi
          echo "Still waiting... ($i)"
          sleep 10
        done

    - name: Print Deployed Public URL
      run: echo "✅ App Deployed at $DEPLOY_URL"

    - name: Add Deploy URL to GitHub Summary
      run: echo "### 🚀 [Eyego App is Live]($DEPLOY_URL)" >> $GITHUB_STEP_SUMMARY

